import {predict,extract,advance} from './engine.js';
const $=id=>document.getElementById(id);let model;let state={accounts:{},rows:[]};const storage='sentinel-browser-demo-v1';
try{const saved=JSON.parse(localStorage.getItem(storage));if(saved?.accounts&&Array.isArray(saved.rows))state=saved}catch{}
function save(){try{localStorage.setItem(storage,JSON.stringify(state))}catch{$('error').textContent='Browser storage is full or unavailable. This session still works, but its history may not be saved.'}}
function cell(value){const e=document.createElement('td');e.textContent=value;return e}
function render(){const rows=state.rows;$('total').textContent=rows.length;$('flagged').textContent=rows.filter(r=>r.decision!=='APPROVE').length;$('average').textContent=rows.length?(rows.reduce((s,r)=>s+r.risk_score,0)/rows.length).toFixed(3):'—';$('rows').replaceChildren();if(!rows.length){const row=document.createElement('tr');const e=cell('Simulate transactions or evaluate your first example.');e.colSpan=5;row.append(e);$('rows').append(row)}for(const r of rows.slice(0,30)){const row=document.createElement('tr');row.append(cell(r.transaction_id.slice(0,16)),cell(r.account_id+' · $'+r.amount.toFixed(2)));const d=cell('');const b=document.createElement('span');b.className='badge '+r.decision;b.textContent=r.decision;d.append(b);row.append(d,cell(r.risk_score.toFixed(3)));const feedback=cell('');const actions=document.createElement('div');actions.className='rowactions';for(const label of ['Legitimate','Fraud']){const button=document.createElement('button');button.className='secondary';button.textContent=r.feedback===label?'✓ '+label:label;button.onclick=()=>{r.feedback=label;save();render()};actions.append(button)}feedback.append(actions);row.append(feedback);$('rows').append(row)}}
function score(tx){if(!Number.isFinite(tx.amount)||tx.amount<=0||tx.amount>1e7)throw Error('Enter a valid positive amount.');if(!/^[a-zA-Z0-9_-]{1,80}$/.test(tx.account_id)||!/^[a-zA-Z0-9_-]{1,80}$/.test(tx.device_id))throw Error('Account and device IDs must use letters, numbers, underscores or hyphens.');const h=Object.hasOwn(state.accounts,tx.account_id)?state.accounts[tx.account_id]:[];const f=extract(tx,h);const result={...tx,...predict(model,f)};Object.defineProperty(state.accounts,tx.account_id,{value:advance(tx,h),writable:true,enumerable:true,configurable:true});state.rows.unshift(result);state.rows=state.rows.slice(0,500);save();return {result,features:f}}
function show({result:r,features:f}){$('result').replaceChildren();const b=document.createElement('span');b.className='badge '+r.decision;b.textContent=r.decision;const v=document.createElement('div');v.className='risk';v.textContent=r.risk_score.toFixed(3);const p=document.createElement('div');p.className='small';p.textContent='Classifier output '+r.fraud_probability.toFixed(3)+' · Anomaly percentile '+r.anomaly_percentile.toFixed(3);const reasons=document.createElement('p');reasons.textContent=r.reason_codes.length?'Policy reasons: '+r.reason_codes.join(', '):'Decision selected from the model risk threshold.';$('result').append(b,v,p,reasons);$('riskbar').style.width=(r.risk_score*100)+'%';$('signals').replaceChildren();for(const [name,value] of [['Prior events · 5m',f.count_5m],['Amount / history mean',f.amount_ratio.toFixed(2)+'×'],['Device unseen · 24h',f.new_device?'Yes':'No'],['Foreign transaction',f.foreign?'Yes':'No']]){const box=document.createElement('div');box.className='signal';box.textContent=name;const strong=document.createElement('b');strong.textContent=value;box.append(strong);$('signals').append(box)}}
$('form').onsubmit=e=>{e.preventDefault();try{$('error').textContent='';show(score({transaction_id:'web_'+crypto.randomUUID(),account_id:$('account').value,timestamp:new Date().toISOString(),amount:Number($('amount').value),device_id:$('device').value,country:$('country').value,home_country:'US'}));render()}catch(e){$('error').textContent=e.message}};
$('generate').onclick=async()=>{$('generate').disabled=true;try{for(let i=0;i<30;i++){const a=Math.floor(Math.random()*15);const suspicious=Math.random()<.2;const tx={transaction_id:'sim_'+crypto.randomUUID(),account_id:'sim_'+a,timestamp:new Date().toISOString(),amount:suspicious?1200+Math.random()*5000:20+Math.random()*250,device_id:suspicious?'device_'+crypto.randomUUID():'usual_'+a,country:suspicious?'GB':'US',home_country:'US',synthetic:true};show(score(tx));render();await new Promise(r=>setTimeout(r,25))}}catch(e){$('error').textContent=e.message}finally{$('generate').disabled=false}};
$('clear').onclick=()=>{if(confirm('Clear the demo transactions, feedback and account history stored in this browser?')){state={accounts:{},rows:[]};save();render()}};
$('export').onclick=()=>{const cols=['transaction_id','account_id','timestamp','amount','decision','risk_score','feedback'];const lines=[cols.join(','),...state.rows.map(r=>cols.map(c=>'"'+String(r[c]??'').replaceAll('"','""')+'"').join(','))];const url=URL.createObjectURL(new Blob([lines.join('\n')],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='synthetic-demo-decisions.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('about').onclick=()=>$('info').showModal();$('closeinfo').onclick=()=>$('info').close();
try{const response=await fetch('./model.json');if(!response.ok)throw Error('Model could not be loaded. Please refresh.');model=await response.json();$('auc').textContent=model.test.pr_auc.toFixed(3);$('model').textContent=model.version+' · Block threshold '+model.threshold.toFixed(3);$('score').disabled=false;$('generate').disabled=false;$('result').innerHTML='<p>Ready. Score an example or simulate a batch of transactions.</p>';render()}catch(e){$('error').textContent=e.message}
